{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "13b3ba69-8f5c-47b8-b793-401679e69ddf",
   "metadata": {},
   "source": [
    "## Adquisición y Simulación de Datos de Tráfico Web"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "fe356d30-979f-441a-8a78-650b5597de01",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "import nltk\n",
    "from nltk.corpus import stopwords\n",
    "from nltk.tokenize import TreebankWordTokenizer\n",
    "from nltk.probability import FreqDist\n",
    "\n",
    "import itertools\n",
    "import string"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9322b085-e271-4496-bb1e-e56be20d9327",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   ID_Contenido               URL  \\\n",
      "0             1  /blog/articulo-1   \n",
      "1             2  /blog/articulo-2   \n",
      "2             3  /blog/articulo-3   \n",
      "3             4  /blog/articulo-4   \n",
      "4             5  /blog/articulo-5   \n",
      "\n",
      "                                              Titulo  Tiempo_en_Pagina  \\\n",
      "0  5 Errores Comunes de Publicidad en Redes Sociales                43   \n",
      "1  API de Google Analytics: Cómo Conectarse con P...               192   \n",
      "2  API de Google Analytics: Cómo Conectarse con P...                70   \n",
      "3  5 Errores Comunes de Publicidad en Redes Sociales               143   \n",
      "4  La Tasa de Rebote Explicada: Cómo Afecta a tu ...                84   \n",
      "\n",
      "   Tasa_de_Rebote  Visitas  \n",
      "0            0.39    13512  \n",
      "1            0.30    12009  \n",
      "2            0.58    12072  \n",
      "3            0.71     5917  \n",
      "4            0.41     2278  \n"
     ]
    }
   ],
   "source": [
    "# Establece la semilla para garantizar la reproducibilidad de los datos simulados.np.random.seed(42)\n",
    "\n",
    "# Definición de las estrategias de contenido temático (muestra de artículos).\n",
    "titulos = [\n",
    "    \"Estrategias de Contenido de Alto Impacto para Agencias Creativas\",\n",
    "    \"La Tasa de Rebote Explicada: Cómo Afecta a tu SEO de Marketing\",\n",
    "    \"API de Google Analytics: Cómo Conectarse con Python y Pandas\",\n",
    "    \"5 Errores Comunes de Publicidad en Redes Sociales\",\n",
    "    \"Guía Completa de la Optimización de Contenido para Vender más\"\n",
    "] * 20\n",
    "\n",
    "# Creación del DataFrame que simula la respuesta de una API de Analítica Web.\n",
    "data = pd.DataFrame({\n",
    "    'ID_Contenido': range(1, 101),\n",
    "    'URL': [f'/blog/articulo-{i}' for i in range(1, 101)],\n",
    "    'Titulo': np.random.choice(titulos, 100),\n",
    "    'Tiempo_en_Pagina': np.random.randint(30, 300, 100), \n",
    "    'Tasa_de_Rebote': np.random.uniform(0.20, 0.80, 100).round(2),\n",
    "    'Visitas': np.random.randint(500, 15000, 100)\n",
    "})\n",
    "\n",
    "# Verificación inicial de la estructura del DataFrame.\n",
    "print(data.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "08cd5dff-0620-45cf-92a0-7de788580c51",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "       ID_Contenido  Tiempo_en_Pagina  Tasa_de_Rebote   Visitas\n",
      "count        100.00            100.00          100.00    100.00\n",
      "mean          50.50            160.31            0.51   7701.96\n",
      "std           29.01             74.52            0.18   3985.44\n",
      "min            1.00             30.00            0.20    638.00\n",
      "25%           25.75             93.50            0.35   4242.75\n",
      "50%           50.50            154.00            0.56   8255.00\n",
      "75%           75.25            224.25            0.65  10986.00\n",
      "max          100.00            296.00            0.79  14969.00\n"
     ]
    }
   ],
   "source": [
    "# Muestra un resumen estadístico de las columnas numéricas\n",
    "print(data.describe().round(2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "07d0c90f-57eb-4d97-b0ca-5225863c4ca2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Artículos de Alto Impacto encontrados: 23 de 100\n",
      "\n",
      "Análisis de Rendimiento Promedio por Título Temático:\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Visitas</th>\n",
       "      <th>Tiempo_en_Pagina</th>\n",
       "      <th>Tasa_de_Rebote</th>\n",
       "      <th>Num_Articulos</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Titulo</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>La Tasa de Rebote Explicada: Cómo Afecta a tu SEO de Marketing</th>\n",
       "      <td>158500</td>\n",
       "      <td>172.14</td>\n",
       "      <td>0.50</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5 Errores Comunes de Publicidad en Redes Sociales</th>\n",
       "      <td>152757</td>\n",
       "      <td>170.15</td>\n",
       "      <td>0.49</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Estrategias de Contenido de Alto Impacto para Agencias Creativas</th>\n",
       "      <td>119381</td>\n",
       "      <td>165.94</td>\n",
       "      <td>0.48</td>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Guía Completa de la Optimización de Contenido para Vender más</th>\n",
       "      <td>179889</td>\n",
       "      <td>150.82</td>\n",
       "      <td>0.54</td>\n",
       "      <td>22</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>API de Google Analytics: Cómo Conectarse con Python y Pandas</th>\n",
       "      <td>159669</td>\n",
       "      <td>144.76</td>\n",
       "      <td>0.53</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                    Visitas  Tiempo_en_Pagina  \\\n",
       "Titulo                                                                          \n",
       "La Tasa de Rebote Explicada: Cómo Afecta a tu S...   158500            172.14   \n",
       "5 Errores Comunes de Publicidad en Redes Sociales    152757            170.15   \n",
       "Estrategias de Contenido de Alto Impacto para A...   119381            165.94   \n",
       "Guía Completa de la Optimización de Contenido p...   179889            150.82   \n",
       "API de Google Analytics: Cómo Conectarse con Py...   159669            144.76   \n",
       "\n",
       "                                                    Tasa_de_Rebote  \\\n",
       "Titulo                                                               \n",
       "La Tasa de Rebote Explicada: Cómo Afecta a tu S...            0.50   \n",
       "5 Errores Comunes de Publicidad en Redes Sociales             0.49   \n",
       "Estrategias de Contenido de Alto Impacto para A...            0.48   \n",
       "Guía Completa de la Optimización de Contenido p...            0.54   \n",
       "API de Google Analytics: Cómo Conectarse con Py...            0.53   \n",
       "\n",
       "                                                    Num_Articulos  \n",
       "Titulo                                                             \n",
       "La Tasa de Rebote Explicada: Cómo Afecta a tu S...             21  \n",
       "5 Errores Comunes de Publicidad en Redes Sociales              20  \n",
       "Estrategias de Contenido de Alto Impacto para A...             16  \n",
       "Guía Completa de la Optimización de Contenido p...             22  \n",
       "API de Google Analytics: Cómo Conectarse con Py...             21  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# --- Segmentación de Alto Impacto ---\n",
    "\n",
    "# Calcula los promedios dinámicamente para el benchmark.\n",
    "tiempo_promedio_dinamico = data['Tiempo_en_Pagina'].mean()\n",
    "tasa_rebote_promedio_dinamico = data['Tasa_de_Rebote'].mean()\n",
    "\n",
    "# Filtra el contenido que supera el rendimiento promedio:\n",
    "# (Tiempo en Página > Promedio) Y (Tasa de Rebote < Promedio).\n",
    "alto_impacto = data[\n",
    "    (data['Tiempo_en_Pagina'] > tiempo_promedio_dinamico) & \n",
    "    (data['Tasa_de_Rebote'] < tasa_rebote_promedio_dinamico)\n",
    "].copy()\n",
    "\n",
    "print(f\"Artículos de Alto Impacto encontrados: {len(alto_impacto)} de {len(data)}\")\n",
    "\n",
    "# --- Análisis de Rendimiento Estratégico (Agrupación) ---\n",
    "\n",
    "# Agrupa los datos originales por el título temático y calcula las métricas promedio.\n",
    "analisis_por_titulo = data.groupby('Titulo').agg({\n",
    "    'Visitas': 'sum',\n",
    "    'Tiempo_en_Pagina': 'mean',\n",
    "    'Tasa_de_Rebote': 'mean',\n",
    "    'ID_Contenido': 'count'\n",
    "}).sort_values(by='Tiempo_en_Pagina', ascending=False).round(2)\n",
    "\n",
    "# Renombra la columna de conteo para claridad\n",
    "analisis_por_titulo = analisis_por_titulo.rename(columns={'ID_Contenido': 'Num_Articulos'})\n",
    "\n",
    "print(\"\\nAnálisis de Rendimiento Promedio por Título Temático:\")\n",
    "analisis_por_titulo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4bf9d33a-0aaa-4fcd-9909-8ec94a4238e8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Palabras Clave limpias generadas con NLTK. Listo para el conteo de frecuencias.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Titulo</th>\n",
       "      <th>Palabras_Clave</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>API de Google Analytics: Cómo Conectarse con P...</td>\n",
       "      <td>[api, google, analytics, cómo, conectarse, pyt...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Guía Completa de la Optimización de Contenido ...</td>\n",
       "      <td>[guía, completa, optimización, contenido, vender]</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Estrategias de Contenido de Alto Impacto para ...</td>\n",
       "      <td>[estrategias, contenido, alto, impacto, agenci...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Estrategias de Contenido de Alto Impacto para ...</td>\n",
       "      <td>[estrategias, contenido, alto, impacto, agenci...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Estrategias de Contenido de Alto Impacto para ...</td>\n",
       "      <td>[estrategias, contenido, alto, impacto, agenci...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                               Titulo  \\\n",
       "1   API de Google Analytics: Cómo Conectarse con P...   \n",
       "6   Guía Completa de la Optimización de Contenido ...   \n",
       "12  Estrategias de Contenido de Alto Impacto para ...   \n",
       "20  Estrategias de Contenido de Alto Impacto para ...   \n",
       "22  Estrategias de Contenido de Alto Impacto para ...   \n",
       "\n",
       "                                       Palabras_Clave  \n",
       "1   [api, google, analytics, cómo, conectarse, pyt...  \n",
       "6   [guía, completa, optimización, contenido, vender]  \n",
       "12  [estrategias, contenido, alto, impacto, agenci...  \n",
       "20  [estrategias, contenido, alto, impacto, agenci...  \n",
       "22  [estrategias, contenido, alto, impacto, agenci...  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Inicializa el tokenizador alternativo (soluciona conflicto en algunos entornos NLTK)\n",
    "tokenizer = TreebankWordTokenizer()\n",
    "\n",
    "# 1. Definición de recursos de limpieza\n",
    "spanish_stopwords = set(stopwords.words('spanish')) \n",
    "puntuacion = string.punctuation\n",
    "\n",
    "# 2. Función para estandarizar el texto y extraer tokens de valor\n",
    "def limpiar_y_tokenizar(titulo):\n",
    "    # a. Tokenizar el texto en minúsculas\n",
    "    tokens = tokenizer.tokenize(titulo.lower())\n",
    "    \n",
    "    # b. Eliminar stopwords y tokens no alfanuméricos\n",
    "    palabras_limpias = [\n",
    "        palabra for palabra in tokens \n",
    "        if palabra.isalnum() and palabra not in spanish_stopwords and palabra not in puntuacion\n",
    "    ]\n",
    "    return palabras_limpias\n",
    "\n",
    "# 3. Aplicación al DataFrame: Genera la columna con las palabras clave limpias\n",
    "alto_impacto['Palabras_Clave'] = alto_impacto['Titulo'].apply(limpiar_y_tokenizar)\n",
    "\n",
    "print(\"Palabras Clave limpias generadas con NLTK. Listo para el conteo de frecuencias.\")\n",
    "alto_impacto[['Titulo', 'Palabras_Clave']].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "094fe559-b61c-4792-ade3-29b5147c28a1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Top 15 Palabras Clave asociadas al Contenido de Alto Impacto:\n",
      "----------------------------------------\n",
      "- cómo: 10 veces\n",
      "- contenido: 9 veces\n",
      "- tasa: 7 veces\n",
      "- rebote: 7 veces\n",
      "- explicada: 7 veces\n",
      "- afecta: 7 veces\n",
      "- seo: 7 veces\n",
      "- marketing: 7 veces\n",
      "- estrategias: 5 veces\n",
      "- alto: 5 veces\n",
      "- impacto: 5 veces\n",
      "- agencias: 5 veces\n",
      "- creativas: 5 veces\n",
      "- guía: 4 veces\n",
      "- completa: 4 veces\n"
     ]
    }
   ],
   "source": [
    "# --- Análisis de Frecuencia de Palabras Clave ---\n",
    "\n",
    "# 1. Aplanar la lista: Convierte la columna de listas (Palabras_Clave) en una sola lista gigante.\n",
    "lista_plana_palabras = list(itertools.chain.from_iterable(alto_impacto['Palabras_Clave']))\n",
    "\n",
    "# 2. Calcular la Distribución de Frecuencias\n",
    "frecuencia_palabras = FreqDist(lista_plana_palabras)\n",
    "\n",
    "# 3. Mostrar las 15 Palabras Clave más Comunes (Insight Táctico)\n",
    "print(\"Top 15 Palabras Clave asociadas al Contenido de Alto Impacto:\")\n",
    "print(\"-\" * 40)\n",
    "for palabra, frecuencia in frecuencia_palabras.most_common(15):\n",
    "    print(f\"- {palabra}: {frecuencia} veces\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
